### ISSUE TITLE
(feature request): include unicode icons

### ISSUE THREAD

**Issue by porterporter** [mincerafter42/mcjarfontgetter#1]
if there could be away to include unicode_page_00.png to unicode_page_ff.png in the exported ttf that would be super useful

if you are able to or have the time to, it would be very helpful

**Comment by mincerafter42** [comment]
Hi, are you trying to get the Unicode icons from the default resource pack or from a custom resource pack? I ask because the Unicode icons in the default resource pack are identical to the [GNU Unifont](http://unifoundry.com/unifont/index.html), so depending on your situation you could just download the GNU Unifont.

**Comment by DN2048** [comment]
I would also like this feature, the unicode icons from the default pack. The GNU Unifont aren't exactly the same. Some characters like ▚ are different.
